### ISSUE TITLE
Cordova platform add fails with 5.0.0

### ISSUE THREAD

**Issue by paulstelzer** [wizpanda/cordova-plugin-firebase-lib#27]
## Describe the bug

If I want to run cordova platform add ios it failes with "Error: pod: Command failed with exit code 31"

## Steps to reproduce

Run `cordova platform add ios`

## Console Logs

```
Failed to install 'cordova-plugin-firebase-lib': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/vsts/agent/2.153.2/work/1/s/packages/app/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

## Plugin Version

5.0.0

Using cordova cli 9.0.0

**Comment by alvaro-octal** [comment]
Try upgrading `pod` to version 1.7.2 by running:

```bash
sudo gem install cocoapods
```

**Comment by sagrawal31** [comment]
Use [v5.1.0](https://github.com/wizpanda/cordova-plugin-firebase-lib/releases/tag/v5.1.0) to make it work. Make sure you have at least `1.5.0` of Cocoapod. Please reopen the issue if you are still getting an error due to this plugin.

**Comment by paulstelzer** [comment]
Thank you! It's still not working (build with Azure Devops) with the same error. I have another cordova plugin with pods in it (pods installing via cordova) and that's working without problems. Btw, you guys doing a great job to maintain the firebase cordova lib - 1000 thumbs up!

I will try it in around three weeks on my personal mac

**Comment by willmero** [comment]
Currently seeing this build error as well running
pod --version 1.7.2
cordova --version 9.0
iOS 5.0.1

**Comment by Birowsky** [comment]
Same here.
pod --version 1.7.3
cordova -v 9.0.0 (cordova-lib@9.0.1)
ios 5.0.1

I'm up for a remote session if you think it'd help. Hit me up anytime.

**Comment by sagrawal31** [comment]
@willmero @Birowsky which version of this plugin you guys are using?

**Comment by Birowsky** [comment]
I’m at 5.1.0

**Comment by Birowsky** [comment]
@sagrawal31  I tried running `cordova platform add ios@5.0.1 --verbose --stacktrace`, and I got a little extra output:

```
Installing plugin "cordova-plugin-firebase-lib" following successful platform add of ios
Found variables for "cordova-plugin-firebase-lib". Processing as cli_variables.
Installing "cordova-plugin-firebase-lib" for ios
Running command: /Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/platforms/ios/cordova/version 
Command finished with error code 0: /Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/platforms/ios/cordova/version 
Running command: /Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/platforms/ios/cordova/version 
Command finished with error code 0: /Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/platforms/ios/cordova/version 
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-firebase-lib on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-firebase-lib" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `sources` - `https://github.com/CocoaPods/Specs.git`
Added source line for `https://github.com/CocoaPods/Specs.git`
Set pods.json for `libraries` - `Firebase/Core`
Added pod line for `Firebase/Core`
Set pods.json for `libraries` - `Firebase/Auth`
Added pod line for `Firebase/Auth`
Set pods.json for `libraries` - `Firebase/Messaging`
Added pod line for `Firebase/Messaging`
Set pods.json for `libraries` - `Firebase/Performance`
Added pod line for `Firebase/Performance`
Set pods.json for `libraries` - `Firebase/RemoteConfig`
Added pod line for `Firebase/RemoteConfig`
Set pods.json for `libraries` - `Fabric`
Added pod line for `Fabric`
Set pods.json for `libraries` - `Crashlytics`
Added pod line for `Crashlytics`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Running command: pod install --verbose
==== pod install start ====

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-мојЧоек`: (``)

Resolving dependencies of `Podfile`

[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    Firebase/Core (= 5.20.2)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Core (= 5.20.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/resolver.rb:88:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

Command finished with error code 31: pod install,--verbose
Failed to install 'cordova-plugin-firebase-lib': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
pod: Command failed with exit code 31
Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/Birowsky/Projects/Personal/GotaGuy/gotaguy-frontend/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

```

**Comment by Birowsky** [comment]
After [some research](https://stackoverflow.com/a/34526412/592641), I ran `pod setup --verbose` before `cordova platform add ios@5.0.1`, and the platform got successfully added. However, it had this warning:

> [!] The `мојЧоек [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-мојЧоек/Pods-мојЧоек.release.xcconfig'. This can lead to problems with the CocoaPods installation
> 
>    - Use the `$(inherited)` flag, or
>    - Remove the build settings from the target.

I believe that's coming from the build.json config, [documented here](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#using-buildjson).

After that, I tried `cordova build ios --verbose --stacktrace`, and got an error:

```
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/FirebaseAuth'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/FirebaseInstanceID'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/FirebaseMessaging'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/GTMSessionFetcher'
ld: warning: 
directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-F/Users/Birowsky/Library/Developer/Xcode/DerivedData/мојЧоек-cmbqhisandqjzzfjnoezgoeadqop/Build/Products/Debug-iphonesimulator/nanopb'
ld: framework not found Pods________
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
        Ld /Users/{obfuscated project path}/cordova/platforms/ios/build/emulator/мојЧоек.app/мојЧоек normal x86_64
(1 failure)
Command finished with error code 65: xcodebuild -workspace,мојЧоек.xcworkspace,-scheme,мојЧоек,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone Xʀ,build,CONFIGURATION_BUILD_DIR=/Users/{obfuscated project path}/cordova/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/{obfuscated project path}/cordova/platforms/ios/build/sharedpch,EMBEDDED_CONTENT_CONTAINS_SWIFT = YES,ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO,LD_RUNPATH_SEARCH_PATHS = "@executable_path/Frameworks"
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/{obfuscated project path}/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

**Comment by sagrawal31** [comment]
Can you provide me a repo reproducing this?

**Comment by Birowsky** [comment]
@sagrawal31 no, it's a private repo.

**Comment by sagrawal31** [comment]
@Birowsky I wanted to say that can you create one blank cordova app, add different plugins which are using and share that repository

**Comment by l3ender** [comment]
Regarding the error for `Failed to install 'cordova-plugin-firebase-lib': Error: pod: Command failed with exit code 31`, I was getting the same until I ran `pod repo update`.

I am seeing the same warning about `LD_RUNPATH_SEARCH_PATHS`, but am able to build successfully. In our scenario, I believe that option is coming from [cordova-plugin-add-swift-support](https://github.com/akofman/cordova-plugin-add-swift-support).

**Comment by sagrawal31** [comment]
@l3ender we don't use `cordova-plugin-add-swift-support` plugin. We'll try to fix this issue.
