### ISSUE TITLE
Installing for ios

### ISSUE THREAD

**Issue by vvarda** [wizpanda/cordova-plugin-firebase-lib#31]
Installing "cordova-plugin-firebase-lib" for **IOS** produces warning **message**:

```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebase-lib': CordovaError: Uh oh!
File already exists at destination "/Users/varda/Desktop/Projects/user-portal-cordova/platforms/ios/Смарт-гроші/Resources/GoogleService-Info.plist" for resource file specified by plugin cordova-plugin-firebase-lib in iOS platform
    at install (/Users/varda/Desktop/Projects/user-portal-cordova/platforms/ios/cordova/lib/plugman/pluginHandlers.js:64:23)
    at ActionStack.process (/Users/varda/Desktop/Projects/user-portal-cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/varda/Desktop/Projects/user-portal-cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/varda/Desktop/Projects/user-portal-cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/varda/Desktop/Projects/user-portal-cordova/platforms/ios/cordova/Api.js:245:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:13)
Failed to restore plugin "cordova-plugin-firebase-lib" from config.xml. You might need to try adding it again. Error: Uh oh!

```

**Comment by sagrawal31** [comment]
Can you do the following:

```bash
rm -rf platforms/android
rm -rf platforms/ios
cordova plugin remove cordova-plugin-firebase-lib
cordova plugin add cordova-plugin-firebase-lib
cordova platform add android
cordova platfor add ios
```
Also, [confirm your cordova environment versions](https://github.com/wizpanda/cordova-plugin-firebase-lib#confirm-your-cordova-environment-versions) and make sure the plugin versions.

**Comment by toFreshMilk** [comment]
i put "cordova platform ios@5.0.0" and

it is shown - --- -- error msg

Running `pod install` (to install plugins)
Failed to install 'cordova-plugin-firebase-lib': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/Users/ci/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/bin/cordova:29:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


what the?
